version: '2.3'
services:
  ipa:
    image: freeipa/freeipa-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
    - "ipa-data:/data:Z"
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    hostname: ipa.noggindev.test
    command: 
    - "--unattended"
volumes:
  ipa-data:
networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: "172.16.238.0/24"
      - subnet: "fd26:d971:9f61:c264::/64"
