---
- name: Install dev packages
  dnf:
      name: "{{ item }}"
      state: present
  with_items:
      - python-flask
      - python-fedora-flask
      - python-sqlalchemy
      - python-openid
      - python-openid-teams
      - python-openid-cla
